### ISSUE TITLE
Resolving ambiguous binary paths

### ISSUE THREAD

**Issue by hndrewaall** [iovisor/bpftrace#1103]
Hello,

Currently trying to get unit tests passing in my environment, and ran into a couple failures that seem to come directly from my having both `/bin/sh` and `/usr/bin/sh` in my `PATH`. Reading the code it seems we explicitly fail in the presence of multiple binaries with the same name in the `PATH`, and I'm wondering if this is desirable. This affects uprobes and USDTs.

Simple reproduction, outside of test cases:

```
$ sudo bpftrace -e "u:sh:f { 1 }"
stdin:1:1-7: ERROR: uprobe target file 'sh' must refer to a unique binary but matched 2
u:sh:f { 1 }
~~~~~~
```

Unit tests relying on environment aside, is this really what we want?  I can think of any number of situations where a user might wish to trace a binary that exists in multiple places on their system. Should we attach to the first? Should we attach to all? Should we warn?

@danobi @acj

**Comment by fbs** [comment]
Was hit by  this too. I think we should do the same your shell does. Use the path to expand and take the first match.

**Comment by acj** [comment]
Using the first match when we're searching through $PATH sounds good to me. The path component also supports wildcards, which is a bit tricky and didn't get fully settled when I was working on #879.

For example, this raises the same questions that were mentioned above:

```
$ sudo bpftrace -e "u:/bin/*sh*:f { 1 }"
```

Should it quietly choose `sh` over `bash` if both are present? Try to attach probes for all matches? Warn? Fail because it's under-specified? I opted for failing and pushing the decision back on the user, which is what led to this issue. My feeling is that we should at least provide a warning in the wildcard case if we're not going to attach probes for every match.

If we want different behavior for wildcards vs. non-wildcards, we'll need to make the code that calls resolve_binary_path a bit smarter, which shouldn't be too bad. It might be a good opportunity to dry up that logic.

I can look into this but would welcome a PR if someone is interested and has time.

**Comment by danobi** [comment]
I think we should always print a warning if we match >1 binary. Otherwise the user will experience silent failures (events not firing).

Thinking about this more (spoke with @hndrewaall offline), I think for !wildcard cases, the using the first match in PATH sounds fine.

For wildcard cases, I need to think about it more. My first thought is that it would be nice to maintain consistency w/ kprobe:
```
$ sudo ./build/src/bpftrace -e 'kprobe:vfs_* { printf("hit %s\n", probe); }'
Attaching 63 probes...
^C^C^C^C
```
But in the kprobe case it's the function, not the binary, and uprobe already support wildcard functions.

We can probably punt on the wildcard decision (always easier to relax constraints) and relax the !wildcard case for now.

**Comment by danobi** [comment]
So I think if a uprobe/usdt target path has a wildcard, we should attach to all matches.

Reason is if a user uses a glob they expect to match more than one thing. Requiring it be
unique would be a strange restriction. We can track this in a follow up issue: #1113
