### ISSUE TITLE
v0.9.4 not available in snapcraft

### ISSUE THREAD

**Issue by joestringer** [iovisor/bpftrace#1179]
Seems like v0.9.4 was released almost a month ago now:
https://github.com/iovisor/bpftrace/releases/tag/v0.9.4

Is there any plan to update the snap?
https://snapcraft.io/bpftrace

**Comment by joestringer** [comment]
For now I worked around it by picking a random build from https://github.com/iovisor/bpftrace/actions

**Comment by fbs** [comment]
We're not the snap maintainers at the moment. @ColinIanKing maintains this, see  #982 

@ColinIanKing we now have a CI setup creates a new quay.io docker image for every push. Would be great to integrate snap with this too so that we can do release and latest snap images. Can I help with integrating the work you did into this repo? Or can I just copy it and use it as a base?

**Comment by danobi** [comment]
#1198 is working towards automated pushes.

**Comment by joestringer** [comment]
Newer 0.10 versions are now available, closing.
