### ISSUE TITLE
use bpftrace uprobe get arguments,arg0 always get my second argument,I don't know why?

### ISSUE THREAD

**Issue by thinkingning** [iovisor/bpftrace#1343]
![image](https://user-images.githubusercontent.com/65694554/82517184-2db85c00-9b4f-11ea-96d2-b98acab31bcd.png)
![image](https://user-images.githubusercontent.com/65694554/82517355-796b0580-9b4f-11ea-948e-ccae4d43cde3.png)
according to pictures,arg0 should be the base,arg0 value is 5.arg1 should be the exponent,arg1 value is 4.
I test a lot of input,arg0 always get my second argument.
I don't know why,please reply me.thank you!

**Comment by mmisono** [comment]
In short, it is impossible to read floating-point arguments.

`arg0`, `arg1`, ... read arguments based on a calling convention. On x86, the calling convention is

> The first six integer or pointer arguments are passed in registers RDI, RSI, RDX, RCX, R8, R9 [...], while XMM0, XMM1, XMM2, XMM3, XMM4, XMM5, XMM6 and XMM7 are used for the first floating point arguments.
> https://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI

So, registers are different for integer or pointer arguments and floating point arguments. I guess other architectures are the same. `arg0`, `arg1`, ... are for accessing integer or pointer arguments. bpftrace cannot access floating pointer registers. I believe there is no kernel support for it.

For the same reason, when using uretprobe, it is impossible to get a return value using `retval` if the value is a floating-point number.

**Comment by thinkingning** [comment]
thank you for answering me.
but when we are tracing some issues,no support for floating pointer will be some fault,I think.

**Comment by mmisono** [comment]
I guess the reason for uprobe not supporting floating values is uprobe is based on kprobe and kernel does not use floating values.

It's a bit tricky, but if you can use USDT, it is possible to store a floating value as a long long value. For example:

```
#include <stdio.h>
#include <sys/sdt.h>

int main(){
    double a = 10.0;

    union {
       long long l;
       double d;
    } u = {.d = a};
    DTRACE_PROBE1(test, probe, u.l);

    return 0;
}
```

then

```
sudo ./src/bpftrace -e 'usdt:./a.out:test:probe { printf("arg: %016llx\n", arg0); }' -c ./a.out
Attaching 1 probe...
arg: 4024000000000000
```

I wonder if bpftrace should support %f formatting in printf.

**Comment by thinkingning** [comment]
The usdt is very helpful,but this code in my project,Does this code affect performance？

**Comment by mmisono** [comment]
The overhead of USDT itself is the same as the upobe (more precisely, USDT is implemented using uprobe). That is, there is overhead only when tracing and the overhead depends on how much this USDT probe fires and what BPF program attached to the probe does. However, in the above example, there is also overhead due to the data preparation for USDT. In other words,

```
    union {
       long long l;
       double d;
    } u = {.d = a};
```

this part is executed no matter if tracing is enabled or not. I guess the overhead is negligible in this example, but if you want to do more complicated data processing, you can use USDT semaphore to see if the program is being traced and run the code for tracing only at the moment. The example of USDT semaphore is https://github.com/iovisor/bpftrace/blob/master/tests/testprogs/usdt_semaphore_test.c

**Comment by thinkingning** [comment]
OK,thank you very much!
