### ISSUE TITLE
can i get millisecond in time() format?

### ISSUE THREAD

**Issue by thinkingning** [iovisor/bpftrace#1406]
time(char *fmt) - Print formatted time
when I use time function,can I get millisecond information?

**Comment by danobi** [comment]
Seems like `strftime` doesn't support this. Seems quite difficult to implement b/c we'd have to work around strftime.

**Comment by fbs** [comment]
I do think having ms/us is useful for the new strftime() call, it should be accurate enough to support atleast ms resolution

**Comment by danobi** [comment]
cc @ember526

**Comment by danobi** [comment]
Related PR: #1387

**Comment by ember526** [comment]
I'll think about it. Though not sure how accurate we can make it.

**Comment by thinkingning** [comment]
I Wrote simple code for my time format，It's enough for me.

    char *mi="%f";

    if (strstr(timestr,mi)) {
      std::string my_string(timestr);
      struct timeb tp;
      ftime(&tp);
      bpftrace->str_replace(my_string,mi,std::to_string(tp.millitm));

      bpftrace->out_->message(MessageType::time, my_string.c_str(), false);
      return;
    }

**Comment by suyuee** [comment]
I suppose the issue here could be that: `time()` can only get its timestimp from userspace when the runtime gets the chance to print it  instread of from BPF the exact moment the event occurs. It's not very clear to me if we can rely on it to offer the precision of millisecond. It might be misleading if we let it give an ouput that is not reliable.
