### ISSUE TITLE
Code not generated for probe: usdt:/full-path:testprobe:testprobe

### ISSUE THREAD

**Issue by Ace-Tang** [iovisor/bpftrace#1466]
I write a example, and the executable file has tracepint
```
$ readelf -n ./tracetest 

Displaying notes found at file offset 0x00000254 with length 0x00000020:
  Owner                 Data size       Description
  GNU                  0x00000010       NT_GNU_ABI_TAG (ABI version tag)
    OS: Linux, ABI: 2.6.32

Displaying notes found at file offset 0x00000274 with length 0x00000024:
  Owner                 Data size       Description
  GNU                  0x00000014       NT_GNU_BUILD_ID (unique build ID bitstring)
    Build ID: b324052bdf781fe5348d1322a4beb249904d4ad8

Displaying notes found at file offset 0x00001080 with length 0x00000048:
  Owner                 Data size       Description
  stapsdt              0x00000034       NT_STAPSDT (SystemTap probe descriptors)
    Provider: tracetest
    Name: testprobe
    Location: 0x0000000000400612, Base: 0x00000000004006e4, Semaphore: 0x0000000000000000
    Arguments: -8@%rax
```

I run bpftrace, show error
```
$ sudo bpftrace -e 'usdt:/home/ace/c/dtrace/tracetest:testprobe {printf("%d: time is %d\n", pid, arg0); }'  
Attaching 1 probe...
Code not generated for probe: usdt:/home/ace/c/dtrace/tracetest:testprobe:testprobe
```

My environment is ubuntu 16.04, and install bpftrace by snap, I not find answer on google

**Comment by fbs** [comment]
I think this might be an issues with snap containment. Would it be possible for you to try the same thing with a build from master? You can [extract one from the docker image](https://github.com/iovisor/bpftrace/blob/master/INSTALL.md#copying-bpftrace-binary-from-docker) or build master.

**Comment by Ace-Tang** [comment]
@fbs  Thanks, but I copy bpftrace binary from docker image, still get the same error
```
docker run -v $(pwd):/output quay.io/iovisor/bpftrace:master-vanilla_llvm_clang_glibc2.23 /bin/bash -c "cp /usr/bin/bpftrace /output"

$ sudo /tmp/bpftrace -e 'usdt:/home/ace/c/dtrace/tracetest:testprobe {printf("%d: time is %d\n", pid, arg0); }'
Attaching 1 probe...
Code not generated for probe: usdt:/home/ace/c/dtrace/tracetest:testprobe
```

Error message it not the same

from snap, it is weird has one more "testprobe"
```
Code not generated for probe: usdt:/home/ace/c/dtrace/tracetest:testprobe:testprobe
```

from docker images
```
Code not generated for probe: usdt:/home/ace/c/dtrace/tracetest:testprobe
```

**Comment by fbs** [comment]
Can you share the source of your test program?

**Comment by Ace-Tang** [comment]
Copy from internet
```
#include <sys/sdt.h>
#include <sys/time.h>
#include <unistd.h>
#include <stdio.h>

static long myclock() {
	struct timeval tv;
	gettimeofday(&tv, NULL);
	// first parameter is provider name, second parameter is
	// tracepoint name
	DTRACE_PROBE1(tracetest, testprobe, tv.tv_sec);
	return tv.tv_sec;
}

int main(int argc, char **argv) {
	while (1) {
		myclock();
		sleep(1);
	}
	return 0;
}
```

**Comment by Ace-Tang** [comment]
It is successfully run on my centos machine, there must be something wrong with ubuntu 16.04
```
#bpftrace -e 'usdt:/root/c/tracetest:testprobe {printf("%d: time is %d\n", pid, arg0); }'
modprobe: FATAL: Module kheaders not found.
Attaching 1 probe...
94359: time is 1597676938
94359: time is 1597676939
94359: time is 1597676940
94359: time is 1597676941
```

**Comment by viktormalik** [comment]
This is an actual bug in bpftrace that seems to be caused by a mismatch in probe name generation. Running with `-d`:
```
# bpftrace -e 'usdt:/root/c/tracetest:testprobe {printf("%d: time is %d\n", pid, arg0); }' -d
...
define i64 @"usdt:/root/c/tracetest:tracetest:testprobe_loc0"(i8* %0) local_unnamed_addr section "s_usdt:/root/c/tracetest:tracetest:testprobe_loc0_1" {
...
```
while the section name that is being searched for in [bpftrace.cpp:876](https://github.com/iovisor/bpftrace/blob/master/src/bpftrace.cpp#L876) is `s_usdt:/root/c/tracetest:testprobe_loc0_0`.

There are 2 differences in section names:
- the LLVM section contains `tracetest:tracetest:testprobe` while the searched name has `tracetest:testprobe`
- the LLVM section has suffix `_1` while the searched suffix is `_0`

Btw, the suffix difference is a regression introduced by commit 43a72e37821815cb86c3fedc1d2280e092c6f895, which explains why it works on CentOS since it has an older version that doesn't contain that commit.

I'll try to investigate the problem and submit a fix.

**Comment by viktormalik** [comment]
So, after some investigation, the problem occurs when namespace is not explicitly specified. According to the reference guide, this is possible:

>Syntax:
>
>```
>usdt:binary_path:probe_name
>usdt:binary_path:[probe_namespace]:probe_name
>usdt:library_path:probe_name
>usdt:library_path:[probe_namespace]:probe_name
>```
>
>Where the `probe_namespace` is optional, and will default to the basename of the binary or library path.

The problem is that `attach_point.ns` is not set in this case, which causes some problems when adding a new probe. I'll post a fix shortly.

In the meanwhile, you can specify the namespace explicitly:
```
bpftrace -e 'usdt:/root/c/tracetest:tracetest:testprobe { printf("%d: time is %d\n", pid, arg0); }'
```
which should work normally (tested on bpftrace v0.11.0 in Fedora 32).
