### ISSUE TITLE
Require libbpf

### ISSUE THREAD

**Issue by fbs** [iovisor/bpftrace#1874]
libbpf is easy to build and package. By requiring it we can remove some build time conditionals and keep stuff simpler.

Vendoring it might be an option too although I'm not sure we will benefit from that

**Comment by danobi** [comment]
+1 for requiring libbpf. We'll probably be using it more as I look at using less bcc. The bpf ecosystem is moving towards libbpf CO-RE over bcc. And we don't use that much bcc stuff anyways (mostly symbol resolution and usdt stuff). Andrii is working on USDT support in USDT and we have some vague plans for a high quality standalone symbolization library (tbd).

One advantage to vendoring libbpf is that we don't need to test libbpf to see which APIs are present (eg --info's `libbpf btf dump`, `libbpf btf dump type decl`). libbpf is also preparing for a v1.0 API breaking release which will probably create more symbol tests for us. If we vendor then we can remove all the build time symbol detection + ifdef's in code because we know exactly what we have.

Not saying we have to vendor -- just something worth considering. There's also value in playing nice w/ packaging ecosystem even though I think their policies are a bit dated...

**Comment by fbs** [comment]
We can probably vendor it the same way we do with gtest. It adds a few lines of cmake but that should be pretty straight forward to do
