### ISSUE TITLE
Support for multiple program files

### ISSUE THREAD

**Issue by hossbeast** [iovisor/bpftrace#1951]
### Is your feature request related to a problem? Please describe.

I have a project that is composed into several modules. Each module defines a bunch of usdt probes, and a bpftrace script for printing the values passed to the probes.

The project builds a few different programs, each of which bundles a few of the libraries.

When I run one of these programs, I want to use all of the probe scripts which apply to that program, given the modules that it links with.

### Describe the solution you'd like

I would like this to work

 > sudo bpftrace -p $pid path/to/scriptA.bt path/to/scriptB.bt path/to/scriptC.bt

It can work just as if the script files were concatenated

### Current behavior

From what I can see, program files beyond the first are silently ignored

**Comment by fbs** [comment]
a quick work around could be to `sudo bash -c  "bpftrace <(cat /vagrant/tools/opensnoop.bt /vagrant/tools/execsnoop.bt )"` (you need bash -c as sudo breaks the process substitution)

The question here is: what does combinng two scripts mean? Does it mean we're compiling 2 separate programs with their own maps, types etc or should it basically concat two files together and make sure the sum is valid?

The former will require a lot of work, we're not capable of handling multiple programs and types like that.

The latter should be easier. The only real issue is our error reporting which isn't capable of handling multiple files but that should be easy to fix. We can just concat them but link offsets in the result to different filenames, e.g. lines 1-10 is file a and lines 11-20 is file b

**Comment by hossbeast** [comment]
For my use-case, it's the latter.

**Comment by danobi** [comment]
As a counter argument, python does the same thing as bpftrace:

```
$  /tmp cat one.py
print("one")
$  /tmp cat two.py
print("two")
$  /tmp python one.py two.py
one
```

I'd argue that concating scripts should not be bpftrace's job. It'll increase complexity within bpftrace (syntax errors as @fbs mentioned). An even simpler workaround would be having bpftrace read from stdin:

```
# cat one.bt two.bt three.bt | bpftrace -
```

This alternative is much more unix-y.

**Comment by hossbeast** [comment]
I don't think the behavior of python matters much (if anything, python and bpftrace should treat this an an error / invalid input, not silently ignore the argument). But leaving that aside.

The idea of passing the concatenated scripts to bpftrace on stdin will work just fine for me.

**Comment by danobi** [comment]
> I don't think the behavior of python matters much (if anything, python and bpftrace should treat this an an error / invalid input, not silently ignore the argument). But leaving that aside.

Actually just realized, the second script is treated as a positional parameter ( https://github.com/iovisor/bpftrace/blob/master/docs/reference_guide.md#9-1--n--positional-parameters ). This is actually what python does too.

So we cannot implement multiple scripts on the command line b/c it would break pos params.

**Comment by fbs** [comment]
There is ofc nothing stopping us from having a `--script` flag (or w/e) that specifies the script to use. This is useless in most cases but I was thinking it could be nice to be able to do `bpftrace --script opensnoop.bt -l` and figure out which probes it attaches to
