### ISSUE TITLE
Building With Multiple Versions Of Clang Installed

### ISSUE THREAD

**Issue by sig1nt** [iovisor/bpftrace#211]
I'm currently attempting to build `bpftrace` on Ubuntu 18.04, and I'm getting a `LLVM Unsupported` error, despite having followed the PPA add instructions in INSTALL.md. Upon further investigations, I realized this is stemming from the fact that I had already installed clang version 4, and now that I had clang version 5, it was being renamed to `clang-5.0`. Can we add some kind of suffix flag to cmake in order to allow for people to build despite this namespacing?

**Comment by gslavin** [comment]
I just hit a similar issue with LLVM versions. If you want to manually modify CMakeLists.txt, you can change this line:

`find_package(LLVM REQUIRED)`

to

` find_package(LLVM <your_version> REQUIRED)`

and then cmake will always pick the LLVM version you expect.

This unfortunately doesn't seem to work with Clang because Clang doesn't specify CLANG_VERSION_MAJOR in the same way LLVM specifies LLVM_VERSION_MAJOR.

If would be nice if cmake at least displayed an error if an invalid LLVM version was chosen.  Something like:

```
find_package(LLVM REQUIRED)
if (${LLVM_VERSION_MAJOR} VERSION_LESS 5)
    message(SEND_ERROR "Unsupported LLVM version found: ${LLVM_INCLUDE_DIRS}")
endif()
```

**Comment by jordalgo** [comment]
Looks like this was mostly addressed here: https://github.com/iovisor/bpftrace/pull/518

Feel free to re-open if that's not right.
