### ISSUE TITLE
bpftrace unable to get symbols for a C++ .so file

### ISSUE THREAD

**Issue by shadyabhi** [iovisor/bpftrace#2118]
### What reproduces the bug?

`bpftrace` is able to list `uprobes`, but when I trace it, `addresses` are not resolved to `symbols`. 

* Listing probes

```
$ sudo bpftrace -l 'uprobe:/export/content/lid/apps/l1proxy-ats/i001/lib64/libats-lib-lixclient.so:*getTreatment*'
uprobe:/export/content/lid/apps/l1proxy-ats/i001/lib64/libats-lib-lixclient.so:_ZN15AtsLibLixClient18LixClientRefresher12getTreatmentERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN14AtsPluginUtils13ClientRequestERlS8_RS6_RNS_3Lix6TargetERiSI_SI_
uprobe:/export/content/lid/apps/l1proxy-ats/i001/lib64/libats-lib-lixclient.so:_ZN15AtsLibLixClient18LixClientRefresher12getTreatmentERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEElS8_RS6_RNS_3Lix6TargetERiSD_SD_
$
```

* Probing function count
```
$ sudo bpftrace -e 'uprobe:/export/content/lid/apps/l1proxy-ats/i001/lib64/libats-lib-lixclient.so:_ZN15AtsLibLixClient18LixClientRefresher12getTreatmentERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN14AtsPluginUtils13ClientRequestERlS8_RS6_RNS_3Lix6TargetERiSI_SI_ { @[func] = count(); }'
Attaching 1 probe...
^C

@[0x7f003af3d1c2]: 104477
```

### Further debugging info

I am unable to provide the actual .so file as it's `internal code` but is there any other debugging info I can provide regarding the environment to help investigate this?

#### Installed the latest one from CentOS Repo on INSTALL page.
```
sudo bpftrace --info
System
  OS: Linux 5.10.41.1-rolling-lts #1 SMP Wed Jun 30 01:06:45 UTC 2021
  Arch: x86_64

Build
  version: v0.13.0
  LLVM: 12.0.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: yes
  probe_read_user_str: yes
  probe_read_kernel: yes
  probe_read_kernel_str: yes
  get_current_cgroup_id: yes
  send_signal: yes
  override_return: no
  get_boot_ns: yes
  dpath: no

Kernel features
  Instruction limit: 1000000
  Loop support: yes
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): yes
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): yes

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
  iter:task: no
  iter:task_file: no
```

**Comment by viktormalik** [comment]
The likely problem here is that the process which makes the probe to trigger (one which links the shared lib) no longer exists at the time you press `^C`.

We're relying on BCC to do the address -> symbol resolution which does it by looking into `/proc/<pid>/maps`. Once the process ends, that file does not exist.

**Comment by shadyabhi** [comment]
@viktormalik  Thank you for replying, however, I don't think that's the case here at all. This is a dynamic library (.so) and it's being used by a continuous running process. Note, I trace on the lib function, not the process. Is that somehow related to the problem? 

What else can I provide as debugging information?

**Comment by viktormalik** [comment]
Hm, not sure what the problem here could be. You could try to print the function name as soon as it is catched:
```
sudo bpftrace -e 'uprobe:/export/content/lid/apps/l1proxy-ats/i001/lib64/libats-lib-lixclient.so:_ZN15AtsLibLixClient18LixClientRefresher12getTreatmentERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKN14AtsPluginUtils13ClientRequestERlS8_RS6_RNS_3Lix6TargetERiSI_SI_ { printf("%s\n", func); }'
```
to see if that changes something (beware, the output will probably be large).

**Comment by xutao323** [comment]
I saw similar issue when adding new tools. I was trying to use `func` in libssl/libcrypto `uretprobe` and found:
1. `func` in `uretprobe` is caller's function name, same as `usym(reg("ip"))`, while I was expecting callee's function name. So `func` and `probe` value are not synced in `uretprobe`. Maybe it's better to add note in `reference guide`. Workaround in the new tools is to store `func` as per-thread value.
2. Sometimes `func` can not be resolved. It's mentioned above symbol resolution needs `/proc/PID/maps`, and I verified this by using `bcc/trace` on `bpftrace`, see steps below. Further investigation shows `bcc` tools resolve symbol before attaching probes and store in python code for reference later, while `bpftrace` do symbol resolve every time `func` is referenced. I think this caused different symbol output between `bcc` and `bpftrace`.

Steps:
a. List uprobes related to symbol resolution:
```
# bpftrace -l 'u:/usr/bin/bpftrace:*' | grep "resolve_usym\|bcc_symcache\|ProcSym.*resolve_addr"
uprobe:/usr/bin/bpftrace:_ZN8ProcSyms12resolve_addrEmP10bcc_symbolb
uprobe:/usr/bin/bpftrace:_ZN8bpftrace8BPFtrace12resolve_usymEmibb
uprobe:/usr/bin/bpftrace:_ZN8bpftrace8BPFtrace12resolve_usymEmibb.cold.1536
uprobe:/usr/bin/bpftrace:bcc_symcache_new
uprobe:/usr/bin/bpftrace:bcc_symcache_new.cold.333
uprobe:/usr/bin/bpftrace:bcc_symcache_refresh
uprobe:/usr/bin/bpftrace:bcc_symcache_resolve
uprobe:/usr/bin/bpftrace:bcc_symcache_resolve_name
uprobe:/usr/bin/bpftrace:bcc_symcache_resolve_no_demangle
```
b. Use `bcc/trace` to trace `bpftrace`, add `exit` tracepoint to verify the `/proc/pid/maps` dependency:
```
# /usr/share/bcc/tools/trace -t \
        'r:/usr/bin/bpftrace:_ZN8bpftrace8BPFtrace12resolve_usymEmibb "%s", retval' \
        'r:/usr/bin/bpftrace:_ZN8ProcSyms12resolve_addrEmP10bcc_symbolb "0x%x", retval' \
        'r:/usr/bin/bpftrace:bcc_symcache_new "0x%x", retval' \
        'r:/usr/bin/bpftrace:bcc_symcache_resolve "0x%x", retval' \
        't:sched:sched_process_exit'
```
c. Run `bpftrace` on 2nd shell, use `uretprobe` as it's closer to program exit, try print `probe` first:
```
# BPFTRACE_NO_USER_SYMBOLS=0 BPFTRACE_CACHE_USER_SYMBOLS=0 bpftrace -e 'ur:libssl:SSL_write {printf("%s\n", probe);}'
Attaching 1 probe...
```
d. Run `echo | openssl s_client -connect localhost:443` on 3rd shell to trigger event.
e. `bpftrace` output showed the `probe` name:
```
uretprobe:/lib64/libssl.so.1.1:SSL_write
uretprobe:/lib64/libssl.so.1.1:SSL_write
^C
```
f. `bcc/trace` output showed no symbol resolve for `probe`:
```
TIME     PID     TID     COMM            FUNC             -
6.016940 38442   38442   bash            sched_process_exit
6.031040 38443   38443   openssl         sched_process_exit
8.157416 38435   38435   bpftrace        sched_process_exit
```
g. Try again using `func` instead of `probe` in 2nd shell `bpftrace`, first resolve showed caller's name and second resolve failed:
```
# BPFTRACE_NO_USER_SYMBOLS=0 BPFTRACE_CACHE_USER_SYMBOLS=0 bpftrace -e 'ur:libssl:SSL_write {printf("%s\n", func);}'
Attaching 1 probe...
s_client_main
0x558b9e72780a
^C
```
h. From `bcc/trace` output, we can see `openssl` exited before the second resolve, thus `ProcSyms` `symcache` all failed. 
```
7.165669 38496   38496   bpftrace        bcc_symcache_new 0x5d28e90
7.166585 38496   38496   bpftrace        _ZN8ProcSyms12resolve_addrEmP10bcc_symbolb 0x1
7.166599 38496   38496   bpftrace        bcc_symcache_resolve 0x0
7.166713 38496   38496   bpftrace        _ZN8bpftrace8BPFtrace12resolve_usymEmibb b'HS\xd2\x05'
7.166715 38504   38504   openssl         sched_process_exit
7.166845 38496   38496   bpftrace        bcc_symcache_new 0x5d5d8b0
7.166863 38496   38496   bpftrace        _ZN8ProcSyms12resolve_addrEmP10bcc_symbolb 0x0
7.166866 38496   38496   bpftrace        bcc_symcache_resolve 0xffffffff
7.166872 38496   38496   bpftrace        _ZN8bpftrace8BPFtrace12resolve_usymEmibb b'\x98S\xd2\x05'
11.90345 38496   38496   bpftrace        sched_process_exit
```
Hope this is helpful.

**Comment by viktormalik** [comment]
Hi @shadyabhi, is the problem still occurring or did you manage to solve it somehow?

@xutao323 thanks for the thorough analysis, this is very helpful! It seems to me that we have 2 problems, I created a new issue for each of them:
1. using `func` in `uretprobe` gives the name of the caller instead of the name of the callee - #2285
2. there's a race condition when using `func` - if the traced binary manages to exit before `func` is handled by bpftrace, an address is returned - #2284

Anyway, neither of these should cause the issue described by @shadyabhi as the caller process should be running continuously.

**Comment by shadyabhi** [comment]
>Hi @shadyabhi, is the problem still occurring or did you manage to solve it somehow?

The problem still exists. I'm happy to provide debugging info if requested on this thread.

**Comment by shadyabhi** [comment]
@viktormalik I feel really bad, I'm sorry I everyone's time here, but I also have a good news for me. I had the issue because the process being traced was under `chroot`. :) 

With that discovery, this issue is good to close, at least for the intent it was originally opened. Once I ran the command bpftrace from chroot env, I was able to see symbols being resolved.
