### ISSUE TITLE
Mangled symbols overlap cannot be disambiguated

### ISSUE THREAD

**Issue by viveksjain** [iovisor/bpftrace#2186]
I see in #1116 that mangled symbols are now supported as probe names. However, this causes issues and unexpected behavior if there is overlap in mangled/non-mangled (C) function names. (Causes rubrikinc/wachy#6)

### What reproduces the bug?

```
~/Developer/rust/wachy/demo$ cat test.cpp
bool main_test() {
  return false;
}

int main() {
  return 0;
}
~/Developer/rust/wachy/demo$ c++ test.cpp
~/Developer/rust/wachy/demo$ nm -g a.out
0000000000201010 B __bss_start
                 w __cxa_finalize@@GLIBC_2.2.5
0000000000201000 D __data_start
0000000000201000 W data_start
0000000000201008 D __dso_handle
0000000000201010 D _edata
0000000000201018 B _end
0000000000000684 T _fini
                 w __gmon_start__
00000000000004b8 T _init
0000000000000690 R _IO_stdin_used
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
0000000000000680 T __libc_csu_fini
0000000000000610 T __libc_csu_init
                 U __libc_start_main@@GLIBC_2.2.5
0000000000000605 T main
00000000000004f0 T _start
0000000000201010 D __TMC_END__
00000000000005fa T _Z9main_testv
~/Developer/rust/wachy/demo$ sudo bpftrace -e 'uprobe:./a.out:main {}'
Attaching 2 probes...
^C

~/Developer/rust/wachy/demo$ sudo bpftrace -e 'uprobe:./a.out:"main()" {}'
No probes to attach
```

I don't see any way to specify that I just want to trace `main`, not `main_test`. `BPFTRACE_NO_CPP_DEMANGLE` doesn't help - it seems to affect the output, not input command line.

Is there some env var/probe option to disable mangled support?

### bpftrace --info
```
System
  OS: Linux 4.15.0-147-generic #151-Ubuntu SMP Fri Jun 18 19:21:19 UTC 2021
  Arch: x86_64

Build
  version: v0.14.1
  LLVM: 12.0.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bpf_attach_kfunc: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libdw (DWARF support): no

Kernel helpers
  probe_read: yes
  probe_read_str: yes
  probe_read_user: no
  probe_read_user_str: no
  probe_read_kernel: no
  probe_read_kernel_str: no
  get_current_cgroup_id: no
  send_signal: no
  override_return: no
  get_boot_ns: no
  dpath: no

Kernel features
  Instruction limit: -1
  Loop support: no
  btf (depends on Build:libbpf): no
  map batch (depends on Build:libbpf): no
  uprobe refcount (depends on Build:bcc bpf_attach_uprobe refcount): no

Map types
  hash: yes
  percpu hash: yes
  array: yes
  percpu array: yes
  stack_trace: yes
  perf_event_array: yes

Probe types
  kprobe: yes
  tracepoint: yes
  perf_event: yes
  kfunc: no
  iter:task: no
  iter:task_file: no
```

**Comment by fbs** [comment]
Core of the problem is

```
        char* demangled_name = cxxdemangle(fun_line.c_str());
        if (demangled_name)
        {
          if (!wildcard_match(prefix + demangled_name , tokens, true, true))
          {
            free(demangled_name);
          }
          else
          {
            free(demangled_name);
            goto out;
          }
        }
```

So we basically match '*main*'.

Guess that instead of 'stupid' matching we should have some function signature aware kind of matching for this so that `myfunc` and `const std::vector<char *> myfunc (bla) const` are matched as `myfunc` and once you add `()` it matches the exact argument signature.
But given how complex c++ functions can be that will be quite a challenge.

We should  also fix the env var as it probably should help in this case, but I wouldn't call it a 'fix' for this

**Comment by fbs** [comment]
> I would be a bit wary of trying to be too smart, I think it's possible for the same binary to have `myfunc` as a C symbol as well as `myfunc()` to be a mangled C++ symbol. Listing a few ideas (not necessarily mutually exclusive):

I don't think its that smart. Instead of having `myfun` match `*myfun*` we'd have `myfun` just match `myfun` but that does require us to be able to extract the function name from the signature which isn't entirely trivial. If `myfun` is overloaded it will match any variant.  `myfunc(int a)` would match a specific overload. But its not as good as:

> 
>     1. Personally I liked the [original proposal](https://github.com/iovisor/bpftrace/issues/687#issuecomment-578411347) that made it very explicit in `probe:/usr/local/bin/dynolog:c++:"*folly::EventBase::run*"`, but presumably that would be more work (and possibly less user friendly).




> 
>     2. One idea is to do this whenever `:` is in the probe name. If you want to match a freestanding `myfunc()` C++ symbol then it could support `::myfunc` which C++ devs should be familiar with. This probably falls in the category of trying to be too smart though, I don't know if it would break in some other scenario.

Not a fan of this one

> 
>     3. Add a new env var to disable this behavior (may be worth keeping it separate from `BPFTRACE_NO_CPP_DEMANGLE` as that does something different). This seems straightforward and useful to me.
> 
> 
> I'd suggest doing 3 as the immediate fix (I can try to look in implementing if necessary), the other options can be discussed separately.

Adding an env var fields like a bit of a hack to me. There is no way to 'set' env vars from programs so that would require extra instructions to be able to use a tool which I don't like. Most of the other env vars we have are to modify reasonable defaults but without this the whole won't work. I know STRLEN one is similar but I don't like that one either ;).

**Comment by viveksjain** [comment]
> I don't think its that smart. Instead of having myfun match *myfun* we'd have myfun just match myfun but that does require us to be able to extract the function name from the signature which isn't entirely trivial. If myfun is overloaded it will match any variant. myfunc(int a) would match a specific overload.

OK I think I misunderstood the proposal. So let's say there is `myfun` (C function), `myfun()` (C++ function) and `myfun(int)` (C++). One of the C++ functions can be selected by specifying full mangled name. But what would the syntax be to probe just the C function?

> Adding an env var fields like a bit of a hack to me.

Glad I haven't starting implementing this yet then.

Another thought based on this discussion: why are we doing fuzzy matching by default anyways? I'd argue that itself is quite unintuitive behavior and it should be explicit. This can be done in various ways, I think the most intuitive might be `*` as a wildcard char (perhaps only supported at beginning/end for now). Case in point, @fbs's comments using `*` to specify the behavior makes it very explicit. Only issue I can see is that `*` might need to be escaped in certain cases, e.g. if you want to match `myfun(int*)` it would have to be specified as `myfun(int\*)`.

**Comment by fbs** [comment]
> > I don't think its that smart. Instead of having myfun match _myfun_ we'd have myfun just match myfun but that does require us to be able to extract the function name from the signature which isn't entirely trivial. If myfun is overloaded it will match any variant. myfunc(int a) would match a specific overload.
> 
> OK I think I misunderstood the proposal. So let's say there is `myfun` (C function), `myfun()` (C++ function) and `myfun(int)` (C++). One of the C++ functions can be selected by specifying full mangled name. But what would the syntax be to probe just the C function?

There isn't any. It will match any function that, after demangle, is named `myfun`. Which is why I like the `c++` prefix in the probe.


> 
> > Adding an env var fields like a bit of a hack to me.
> 
> Glad I haven't started implementing this yet then.
> 
> Another thought based on this discussion: why are we doing fuzzy matching by default anyways? I'd argue that itself is quite unintuitive behavior and it should be explicit. This can be done in various ways, I think the most intuitive might be `*` as a wildcard char (perhaps only supported at beginning/end for now). Case in point, @fbs's comments using `*` to specify the behavior makes it very explicit. Only issue I can see is that `*` might need to be escaped in certain cases for functions dealing with pointers, e.g. if you want to match `myfun(int*)` it would have to be specified as `myfun(int\*)`.

Guess we didn't think it through enough and just went for the easiest option. Currently the symbols are demangled and then `uprobe:myfunc` is matched like the user wrote `uprobe:*myfunc*`. This avoids having the extract just the function name from the signature. E.g. `*myfunc*` works for both  `const char * myfunc(int a, int b)` and `int myfunc(std::another_complex_<<<<<<type>>>>> y)`. The downside is that is also matches `myfunc2` which causes this bug.

-------

With the `c++` prefix we should be able to do this.

Say we have a table like:

```
1 T myfunc
2 T __Z6myfuncPc
3 T __Z6myfunci
4 T __Z6myfuncv
5 T __Z8myfunc_2i

demangled:

1 T myfunc
2 T myfunc(char*)
3 T myfunc(int)
4 T myfunc()
5 T myfunc_2(int)
```

Using the `:c++` approach:

1. `u:bin:myfunc`: will only match 1
1. `u:bin:__Z6myfuncPc`: will only match 2
1. `u:bin:c++:myfunc` will match any symbol matching `*myfunc(*` after demangle so 2,3,4

note that 3. requires some modification to the matching. The current behaviour is to match `*myfunc*` which would include 5. For a first iteration that wouldn't be bad imo.

The only downside is that it will break existing scripts which rely on `u:bin:"myfunc()" but building some kind of backwards compatibility that 'fixes' that seems like its just as error prone. E.g. we'd have to check if it contains 'invalid' symbols like `()` and `::` and then convert it to a c++ probe.

**Comment by viveksjain** [comment]
Ah so you'd still want the `c++` prefix, then that seems fine. If we want to match the exact function name, I think it should handle functions inside namespaces too, so I'd imagine a regex like `.*( |:)myfunc\(.*` should do it, although knowing C++ there's almost certainly more edge cases.

Next question is who would be able to implement that change? It's too large for me to do so. I don't mean to sound like a broken record, but if there's no volunteers for that, I would still prefer to add the env var as an immediate simple fix - and it can easily be removed once the proper solution is implemented.

**Comment by viktormalik** [comment]
I'm fine with allowing the `:c++` prefix, but I wouldn't force users to do so in this case, as name mangling is not a C++ specific feature. For the above example, I'd prefer `u:bin:myfunc` to match 1-4, i.e. all functions named `myfunc`. Still, bpftrace's purpose is to trace binaries, not to trace C programs specifically. I know that we wouldn't be able to attach to non-mangled `myfunc` only, but it feels like a very rare use-case to me.

On the other hand, I like the idea of specifying probes by full signatures in future.

Anyway, once we agree on the approach to take, I can work on the implementation.

**Comment by fbs** [comment]
> I'm fine with allowing the `:c++` prefix, but I wouldn't force users to do so in this case, as name mangling is not a C++ specific feature. For the above example, I'd prefer `u:bin:myfunc` to match 1-4, i.e. all functions named `myfunc`. Still, bpftrace's purpose is to trace binaries, not to trace C programs specifically. I know that we wouldn't be able to attach to non-mangled `myfunc` only, but it feels like a very rare use-case to me.

How confident are we that these generic rules work on all languages/platforms/architectures we want to support? If we do language specific probes (i.e. the `:c++:`) the rules are simple:

- `u:bin:myfunc` matches only the symbol `myfunc`, not `myfunc2` or `__Z6myfuncv`. If you want to match `myfunc()` you have to use `__Z6myfuncv`.
- `u:bin:lang:myfunc` will enable language specific features. This has two benefits: 1. we can implement language(/platform) specific handling for the demangling making sure we dont waste time trying demangle approaches that don't work[^1]. We can implement language specific parsing as the rules for extracting the function name from a C++ signature might not work for rust or golang. Additionally knowing the language would allow for language specific features in probes in the future, e.g. access to `*this` in c++. Having it language specific will probably also help keeping the implementation  simpler and easier to follow.


[^1]: we might even get away with mangling the probe and falling back to some kind of smart matching instead of trying to demangle the whole binary and match that way, depending on how expensive all this is.

**Comment by viktormalik** [comment]
> > I'm fine with allowing the `:c++` prefix, but I wouldn't force users to do so in this case, as name mangling is not a C++ specific feature. For the above example, I'd prefer `u:bin:myfunc` to match 1-4, i.e. all functions named `myfunc`. Still, bpftrace's purpose is to trace binaries, not to trace C programs specifically. I know that we wouldn't be able to attach to non-mangled `myfunc` only, but it feels like a very rare use-case to me.
> 
> How confident are we that these generic rules work on all languages/platforms/architectures we want to support? 

Good point. Each language probably has different rules for mangling, so in the end, it is a language-specific feature. In that case, I agree with using the `:lang` prefix and if it's not used, then the probe is matched exactly as it appears in the binary.

Just a question, do we want to support this in probe listing? E.g.:
```
# bpftrace -l 'u:bin:*'
uprobe:bin:_ZN3Bar3funEi
uprobe:bin:_ZN3Foo3funEi

# bpftrace -l 'u:bin:c++:*'
uprobe:bin:c++:Bar::fun
uprobe:bin:c++:Foo::fun
```
And, once we support function signatures:
```
# bpftrace -l 'u:bin:c++:*'
uprobe:bin:c++:Bar::fun(int)
uprobe:bin:c++:Foo::fun(int)
```
