### ISSUE TITLE
"bpftrace --info" segfault on kernel built with v1.24 pahole

### ISSUE THREAD

**Issue by aaronlu** [iovisor/bpftrace#2489]
Hello,

Ever since dwarves was upgraded to v1.24 on Fedora, bpftrace on the self built kernel stops working and complained something like:

```
$ sudo bpftrace taskgroup.bt 
taskgroup.bt:24-26: ERROR: kfunc:enqueue_task_fair: BTF data not available
```
And if I run "bpftrace --info", I got:
```
$ sudo bpftrace --info
System
  OS: Linux 6.2.0-rc4-00077-gd368967cb103 #3 SMP PREEMPT_DYNAMIC Sun Jan 29 14:37:21 CST 2023
  Arch: x86_64

Build
  version: v0.16.0
  LLVM: 12.0.0
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libbpf bpf_prog_load: no
  libbpf bpf_map_create: no
  libdw (DWARF support): no

Segmentation fault
```
If I downgrade dwarves to v1.23, everything works again. Not sure what problem it is.
BTW, bpftrace was downloaded from this release channel. Thanks.

**Comment by viktormalik** [comment]
Hard to debug without more information but there're some weird things there.

> $ sudo bpftrace taskgroup.bt taskgroup.bt:24-26: ERROR: kfunc:enqueue_task_fair: BTF data not available

This looks more like a problem with you kernel build (no BTF). Can you run:
```
$ ls -l /sys/kernel/btf/
```
and paste the output?
 
> libbpf bpf_prog_load: no

This suggests an old libbpf in your distro, which could actually be the problem. pahole 1.24 had a [problem](https://lkml.org/lkml/2022/8/24/1090) on some systems which required to use `--skip_encoding_btf_enum64` during the kernel build, otherwise BTF could not be generated.

Maybe you could try to build bpftrace from the latest master. That will use the latest libbpf and could perhaps solve the problem.

**Comment by viktormalik** [comment]
> As for the libbpf version, it is 0.7.0 on both the host and the VM, they are both Fedora 36:

0.7.0 is rather old and IIRC doesn't have `bpf_prog_load` so it's probably correct. That would still point to the problem with BTF enum64 support introduced in pahole 1.24.

Can you also give `bpftool --version`?

**Comment by aaronlu** [comment]
Just to be clear, I do not have bpftool installed on my host but I've it installed on my guest:
```
[aaron@fedoravm ~]$ bpftool --version
bpftool v7.1.0
using libbpf v1.1
features: libbfd, libbpf_strict, skeletons
```

Another thing I just found: if I use the distro provided bpftrace, then the "libbpf bpf_prog_load" would be "yes", but it still segfaulted. It appears to me, the bpftrace binary I downloaded here doesn't use system's libbpf. Here is the output of "bpftrace --info" when using distro's bpftrace:
```
[aaron@fedoravm ~]$ sudo /usr/bin/bpftrace --info
System
  OS: Linux 6.2.0-rc4-00270-g382e8c1b4f7c #8 SMP PREEMPT_DYNAMIC Mon Jan 30 21:22:38 CST 2023
  Arch: x86_64

Build
  version: v0.16.0
  LLVM: 14.0.5
  ORC: v2
  foreach_sym: yes
  unsafe uprobe: no
  bfd: yes
  bcc_usdt_addsem: yes
  bcc bpf_attach_uprobe refcount: yes
  bcc library path resolution: yes
  libbpf btf dump: yes
  libbpf btf dump type decl: yes
  libbpf bpf_prog_load: yes
  libbpf bpf_map_create: yes
  libdw (DWARF support): no

Segmentation fault
```

Thanks for taking a look and hopefully I've made the codeblock right :-)

**Comment by aaronlu** [comment]
Hi Viktor,

> > As for the libbpf version, it is 0.7.0 on both the host and the VM, they are both Fedora 36:
> 
> 0.7.0 is rather old and IIRC doesn't have `bpf_prog_load` so it's probably correct. That would still point to the problem with BTF enum64 support introduced in pahole 1.24.

Yes, you are right. I tried building the kernel by adding --skip_encoding_btf_enum64 to pahole and then the problem is gone. I wonder, what is the problem here? Is bpftrace unable to handle enum64 or Linux kernel should not encode enum64 or pahole has a bug?

**Comment by viktormalik** [comment]
Hi Aaron,

the problem is that pahole 1.24 generates BTF with enum64 entries which are only supported by libbpf 1.0+. Since bpftrace relies on libbpf to load BTF, this is the root of the failures. The reason why you were able to parse the BTF file with bpftool is that you used bpftool from your host which is based on libbpf 1.1 (already supporting enum64).

Concerning `bpf_prog_load`, AFAIK it was added in libbpf 0.8. If you downloaded the latest bpftrace binary, we're building it against the latest libbpf (linked statically).

**Comment by aaronlu** [comment]
Hi Viktor,
 
> the problem is that pahole 1.24 generates BTF with enum64 entries which are only supported by libbpf 1.0+. Since bpftrace relies on libbpf to load BTF, this is the root of the failures. The reason why you were able to parse the BTF file with bpftool is that you used bpftool from your host which is based on libbpf 1.1 (already supporting enum64).

Thanks for the explanation.

> 
> Concerning `bpf_prog_load`, AFAIK it was added in libbpf 0.8. If you downloaded the latest bpftrace binary, we're building it against the latest libbpf (linked statically).

That's great.
I've tried the 0.17.0 binary and now it works well with kernel built with v1.24 pahole :-)

I'm closing this issue, thanks again.
