### ISSUE TITLE
Spurious lost events warnings + duplicate/out-of-order/silent lost events

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#2646]
After the changes in #2475, I'm seeing a lot of spurious lost event warnings.

We should sort this out before pushing the next release.

### What reproduces the bug?
```
# bpftrace -e 'kretprobe:vfs_read { printf("func: '%s'\n", func); exit(); }' 
Attaching 1 probe...
func: vfs_read
Lost 4595 events
```

**Comment by xh4n3** [comment]
@ajor could you please show me the output of `bpftrace --info`?

**Comment by ajor** [comment]
This bug only seems to appear on high frequency probes. I've seen it with both the func and the kstack builtins, probably because these require symbolication and so are slow to execute in user space.

I was able to reproduce it with another probe (although less reliably):
```
$ sudo ./build/src/bpftrace -e 'kprobe:cpuidle_enter_state { @c = count(); printf("func: '%s'\n", func); exit(); }'
Attaching 1 probe...
func: cpuidle_enter_state
Lost 42 events


@c: 6574
```

I also found another more serious bug - duplicate prints:
```
$ sudo ./build/src/bpftrace -e 'kprobe:cpuidle_enter_state { @c = count(); printf("func: '%s'\n", func); exit(); }'
Attaching 1 probe...
func: cpuidle_enter_state
func: cpuidle_enter_state


@c: 2384
```
I'd guess that either the first exit event is being lost (although there are no lost events warnings) or the events are arriving out of order.

Full logs at: https://pastebin.com/raw/AYZMpk8e. The lost events bug appears once and the duplicate prints twice in this run of 30 bpftrace sessions.

For comparison, I reverted commit 67d4bd7c79839ca9563a6be155f0413da519f482 and saw these bugs 0 times over 100+ runs.

My bpftrace info: https://pastebin.com/raw/g4XnR1a6

**Comment by xh4n3** [comment]
While still investigating this issue, I'd like to share some bare thoughts first. Please correct me if anything is incorrect.

Calling exit() in BPF programs doesn't necessarily exit the BPF programs right away. If we add a debugf() before the exit(), we will see only one line log from the standard output, but many lines of debug output from the trace pipe. It proves that there is a slight delay between calling exit() and the BPF program's complete stop.

The PR #2475 uses a event_loss_counter to record bpf_ringbuf_output() failure in the kernel space. As long as the BPF program keeps running, this counter keeps being updated. I'd guess these losses came from bpftrace's teardown process.

This differs from the old perf_event's event loss handling logic. perf_event does not have a counter in the kernel space, but a perf_event callback mechanism. We may just haven't observed the losses on the BPF side yet. Besides, for perf_event, once exit() is received by the userspace, bpftrace will short-circuit the event handling, making event losses caused by perf_event processing less likely to happen.

I'm not sure if these make sense, next, I will try to add a loss counter to perf_event to prove it.

**Comment by xh4n3** [comment]
IIUC, the duplicated prints happen because the BPF program is executing parallelly on all CPU cores. There're chances two printf()s are inserted into the ring buffer before any exit() is inserted. [Since the ring buffer only has one shared buffer for all CPU cores, the event order is guaranteed.](https://nakryiko.com/posts/bpf-ringbuf/) Then when bpftrace consumes the events, the first two printf()s are printed out first. 

The reason we do not notice this on perf_event: perf_event buffers are not shared, bpftrace processes events for each CPU [on a one-by-one basis](https://github.com/iovisor/bpftrace/blob/v0.18.0/src/bpftrace.cpp#L1344-L1347)

**Comment by xh4n3** [comment]
It seems that the above two issues are caused by the inconsistency in the current implementation of ringbuf and perf_event, rather than being bugs per se. I'm wondering if it is a good idea to write a documentation to inform bpftrace users about these differences. How you do think? @ajor @viktormalik @danobi

**Comment by danobi** [comment]
Yeah I concur. I suspect it's b/c there's a single ringbuf and it keeps going even after the async exit is sent by the prog. And for perf events, we only process a single perfrb at a time (given ncpu perfrbs). So there is some natural undercounting by perfrb. And some natural overcounting by ringbuf.

We might be able to codegen a barrier shared between all the cpus for ringbuf so that progs stop sending events to the ringbuf after exit has been sent, but I also suspect that would have bad cache effects and cause perf issues.

**Comment by danobi** [comment]
I'm not sure what the documentation would look like to be honest. Maybe we could have generic docs about how relying on async events may not be a good idea if you want full fidelity. Helpers like `count()` may be a better option for those cases.
