### ISSUE TITLE
Add `EXPECT_TEXT` runtime test directive

### ISSUE THREAD

**Issue by danobi** [iovisor/bpftrace#2842]
Similar to https://github.com/iovisor/bpftrace/issues/2841, would be great to have an `EXPECT_TEXT` directive that compared output with contents of of a checked in file. This would make testing the human readable text output of helpers like `hist()` more tractable.

A good candidate is adding more tests for `hist()` cuz that's mostly been missing. See https://github.com/iovisor/bpftrace/pull/2831

**Comment by luigirizzo** [comment]
See https://github.com/iovisor/bpftrace/pull/2845 for a possible implementation of this and EXPECT_JSON features.

I have used `EXPECT_FILE` instead of `EXPECT_TEXT` as keyword, because
the latter seems ambiguous (is the rest of the line plaintext to compare, or a filename?)

But I have no strong opinions and this is a trivial change.

I
