### ISSUE TITLE
pre- and post-increment

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#412]
following on from #53, this would make $x++ and $x-- work. And this:

`bpftrace -e 'k:vfs_read { @++ }'`

I think we'd also want to use this in the tutorial and one-liners to aid learning, since it's familiar. If this is easy to add, let's add it now so that we can start using it in docs sooner.

**Comment by dalehamel** [comment]
Is there an error in your example? Should it be `@x[KEY]++` and/or `$x++`?

I believe I understand the codepaths needed to implement this, and I agree it would be a useful shorthand. This is probably also easier to implement than #53, which would require more changes to the parser (i think).

So the cases that would need to be handled here would be:

* `expr ++`
* `expr --`
* `++ expr`
* `-- expr`

The semantic analyzer would verify that expr evaluates to an integer, and then perform the operation. I think there will probably be some nuance to how the pre operations would work

**Comment by brendangregg** [comment]
Yes, it may be easier than #53. So @x[KEY]++ and @x++ should both work. Try this to see what I mean:

`bpftrace -e 'k:vfs_read { @ = @ + 1 }'`

Would rather that be "++". Thanks for checking it out!

**Comment by brendangregg** [comment]
@dalehamel did you (or anyone else) want to have a crack at this? I might want to make it 0.9 tagged, as I suspect we'll adopt a lot in the example documentation, so better to get people used to it sooner.

**Comment by dalehamel** [comment]
@brendangregg yes I'd like to take a crack at this, hopefully within the next two weeks.

What is the targeted timeline for 0.9? If it's more imminent then that I might not be able to deliver something on time.

**Comment by brendangregg** [comment]
About two weeks from now sounds good for 0.9.

**Comment by dalehamel** [comment]
For simple cases, I believe this should be easy to implement:

```
$x++
$x--
$var = ++$x
$var = --$x
```

As in each of these cases, they are just evaluating an expression, or evaluating an expression and then assigning it, which bpftrace's parsing and semantic analysis lends itself very nicely to. In fact, the expressions `$x++` and `$x--` are actually (abstractly) shorthands for:

```
$x = ++$x
$x = --$x
```

For more nuanced cases, I'm not sure if the current parser semantic analyzer can easily handle them:

```
$var = $x++
$var = $x--
```
As the behavior that bpftrace lends itself to is to fully evaluate the right hand side before doing the assignment to the left hand side, which is what the behavior of a pre-increment is. This is not a problem if there is no assignment, as in my examples above.

For the simple pre-increment operations, nothing fancy is needed, we can basically literally alias them to have an RHS of the literal `1` (or -1). For post-increment operations, we will need to have the expression evaluate to (or return) the value of the LHS, but still perform the increment operation.

Having a literal for the RHS may be simpler, but I think it's probably short-sighted, and we will want to create a new type of operation called `CompoundOp` that can also handle the cases of #53 which have a very similar shape of needing to evaluate *and* assign.

The scope of these changes might then be:

* Declare these new operation types in `ast.h`
* Define tokens for `PLUSPLUS`, `MINUSMINUS` in `ast.cpp`, analogously to `binop` and `unop`
* Create four cases in the parser, handling the pre and post versions of both of these operator types
* Add a case to the semantic analyzer for `CompoundOp` 
* Add codegen that handles CompoundOp, where the literal `1` is either added or subtracted, and the return value is assigned either before doing this (post increment) or after doing this (pre-increment). I think it will need its own codegen to handle these nuances, which will require code duplication of any otherwise already supported `Binop`

The nuance here is that last step. We will want to be able to return a value for what the expression actually *evaluates* to, for using it in an assignment. But, we will *also* want to be able to directly mutate the variable passed in, either before or after "returning". 

I'll try and come up with a solution that is extensible for #53 as it really smells like there is a lot of overlap here. Afterall, `$x++` is basically a shorthand for `$x += 1`, so solving for the latter should get us the former relatively cheaply. If I'm able to reason something out, I'll look at submitting changes for #53 as well.

**Comment by brendangregg** [comment]
Thanks; I think just supporting

```
$x++;
$x--;
```

As the first step would be a big help, and get used often, eg:

```
bpftrace -e 'k:vfs_r* { @[probe]++ }'
bpftrace -e 'k:vfs_read { @++ }'
```

**Comment by dalehamel** [comment]
If we're fine with a hacky first pass that supports just the simple cases of "self increment self", I'm totally on board with that and can get something cranked out pretty soon - I'll turn my efforts in this direction.

I'd be happy to follow up with a more complete implementation of a scope similar to what I described, to actually close off #412 and #53 while handling all cases idiomatically and is pedantically tested. This could go into a 1.0 or some other next release, on a more relaxed schedule.

**Comment by dalehamel** [comment]
I have a very hacky first pass working, such that:

```
```

**Comment by brendangregg** [comment]
Yes, it should initialize to zero. These should work:

```
bpftrace -e 'k:vfs_r* { @[probe]++ }'
bpftrace -e 'k:vfs_read { @++ }'
```

**Comment by dalehamel** [comment]
What I wanted to confirm was if this should also be the behavior for variables (implicitly declaring them and initializing them to 0), as maps are handled a bit differently and not exactly "declared" per se, from my read of the code. I agree that it's simplest to keep the behavior consistent between variable and map examples.

Anyways, I have some slapdash code that implements all of these simple examples successfully. I'll have a PR up soon (hopefully tomorrow) after a bit more cleanup and I've written some basic tests and updated the docs, it's not exactly DRY or elegant, but it'll do for now. 

Should definitely be ready for the 0.9 release, as the tricky bits are now done.

**Comment by dalehamel** [comment]
I have #439 up which is in good enough shape to review. 

It addresses the cases discussed, and the examples provided above work verbatim, as indicated in the reference guide docs that are added.

**Comment by ajor** [comment]
I think we do want to get this one finished off as this operator isn't behaving as I would expect at the moment (i.e. returning a value).

If no one actually cares about the return values of this expression yet then we should just use the `$x += 1;` syntax from #53 and not support this ++/-- syntax.

**Comment by dalehamel** [comment]
@ajor that was actually the behaviour of the PR I reverted, when I moved it into the parser. (Actually returning a value, that is).

We could revive that code to *just* handle the ++ and — operators, and then use the parser approach for the other compound operators.

Another limitation of ++ and — implemented within the parser is that they cannot be used for both post and pre incrementing.

I had worried I was over complicating things when I saw that the other compound operators could be done in the parser, and opted for the simpler approach since it seemed to match most use cases.

If we don’t care about both post and pre incrementing, and want the support for returning a value, then my reverted PR does the trick.

If we want both post and pre increment to work as expected I can probably add that pretty easily.

To extend support to other compound operators (+=, -=, etc) I had planned to just do those in the parser to solve #53.

What approach would you suggest? I’d be happy to wrap these off.

**Comment by ajor** [comment]
Ah I didn't realise your old patch did that. For the pre and post increment/decrement operators I do think we'd need special codegen to get the right behaviour.
I actually did a little on this just now (see https://github.com/ajor/bpftrace/commit/c0d05e4661898b6751225e544879579c716dacf1). A couple of comments on what I was thinking:
- the operators should be classed as Unops
- they should be able to take any expression type as arguments, not not maps and variables

The parser approach seems good for the += stuff.

**Comment by dalehamel** [comment]
@ajor so would you like to wrap this one off? Don't want to step on your toes if you're already working on it.

I can focus on the other compound operators, and i'd be happy to review your change as i've touched the same code and spent a lot of time thinking about it.

**Comment by fbs** [comment]
Looks like this has been fixed, closing
