### ISSUE TITLE
Unlimited probe enabling is a time bomb

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#502]
Currently bpftrace doesn't limit the number of probes that can be enabled so with a one liner it is trivial to light up tens of thousands of probes. Owing to a known issue with bpf probe teardown (referenced in the bcc bug created by @brendangregg - https://github.com/iovisor/bcc/issues/1317 )this can render a system completely unusable. For example, I enabled `kprobe:*` on my 32 way system and after an hour of 90% system mode usage I had to reboot the box. Obviously, this is a seriously dangerous issue to leave exposed.

My view is that bpftrace should probably implement a probe limit that can be overridden by the user - possibly set it to 1000 like bcc currently does (for its python interface anyway in python/bcc/__init__.py).

**Comment by dalehamel** [comment]
FWIW I have hit open file ulimits and had to raise it a number of times when i've tried to simultaneously enable more than around 600 probes, I would guess because bpftrace hits `ulimit -n`, which defaults to 1024.

Raising it to 4096 I was able to attach the probes I wanted to, but it definitely was slow in tear-down.

This somewhat already has the behavior that you specified, assuming they maintain the default system ulimit for most processes around 1024, and can be overridden.

Should this really be bpftrace's problem to solve?

**Comment by tyroguru** [comment]
At the company I work for the default soft limit for max open files is 64k  It's not bpftrace's problem to solve as it is fundamentally a bpf problem but it needs to enforce a limit like bcc does. Any tool where you can kill your system in "normal" operational mode is a poor one.

**Comment by dalehamel** [comment]
> default soft limit for max open files is 64k

Ah yes, perhaps we should make this tunable then.

Would you suggest that it be a command line flag to override the defaults?

**Comment by tyroguru** [comment]
Other people may have different options I guess but unless we were going to provide a command line option to set tunables and expose a bunch of tunables that change behaviour (e.g., `bpftrace -s max_enabled_probes = 10000`) I'd prefer to do it via an environment variable.

**Comment by brendangregg** [comment]
I'd make it an environment variable, which makes it less visible than command line options, but that's a good thing: this is temporary until the kernel supports batch probe enabling/disabling (I thought FB was going to do it, but you've been busy building BTF). And yes, normal behavior shouldn't cause crashes.

Also note that in the meantime, some of the bcc/bpftrace tools can be run as Ftrace tools from https://github.com/brendangregg/perf-tools . I always use my Ftrace funccount, since it can trace every kernel function immediately, and stop immediately. (I need to do some updates to those Ftrace tools, since there are more features added they don't use yet.)

**Comment by dalehamel** [comment]
To add my 2 cents, I agree with the environment variable approach. Just checking for the environment variable and overriding a hardcoded constant is an easy and familiar pattern.
