### ISSUE TITLE
ntop can't handle saddr

### ISSUE THREAD

**Issue by brendangregg** [iovisor/bpftrace#521]
This should work (this tracepoint was added in Linux 4.16):

```
# bpftrace -e 't:sock:inet_sock_set_state { @[ntop(args->family, args->saddr)]++ }'
ntop() only supports integer arguments (none provided)
ntop() only supports integer arguments (none provided)
```

fields:

```
# bpftrace -lv t:sock:inet_sock_set_state
tracepoint:sock:inet_sock_set_state
    const void * skaddr;
    int oldstate;
    int newstate;
    __u16 sport;
    __u16 dport;
    __u16 family;
    __u8 protocol;
    __u8 saddr[4];
    __u8 daddr[4];
    __u8 saddr_v6[16];
    __u8 daddr_v6[16];
```

I think it's because of the array? Maybe #285 will fix it?

**Comment by dalehamel** [comment]
Yes I believe you are correct that bpftrace is seeing it as type `none` because the case for the actual type here (constant array) is not handled.

I believe you're also correct that #285 would fix it, as I added this blurb: https://github.com/iovisor/bpftrace/blob/f90748662f89f1e575bd0005237737e15cefecd3/src/clang_parser.cpp#L99

Right now if you tried to say, cast this to an int32 it wouldn't even be able to do that, as the clang parser flags it as type `none`, which is indicated by the error message.

I did run into cases like this during and before implementing #285.

I'll bump #285 up in my preview list

**Comment by brendangregg** [comment]
Now we have #285 (thanks!), we're closer to doing this, but I think we need both #553 and #554!

```
# bpftrace -e 'tracepoint:sock:inet_sock_set_state { @[ntop(2, args->saddr[0])]++ }'
Attaching 1 probe...
^C

@[100.0.0.0]: 5
@[127.0.0.0]: 20
```

That's just the first u8, the saddr[0]. It's a pity the tracepoint only makes these u8's available. So if ntop() stays as pass-by-value, then we need to take the address of the u8, cast it as a u32, then dereference again:

```
# bpftrace -e 'tracepoint:sock:inet_sock_set_state { @[ntop(2, *(int *)&args->saddr[0])]++ }'
```

If ntop() becomes pass-by-reference (since that'll make IPv6 easier), it becomes either:

```
# bpftrace -e 'tracepoint:sock:inet_sock_set_state { @[ntop(2, &args->saddr[0])]++ }'
or:
# bpftrace -e 'tracepoint:sock:inet_sock_set_state { @[ntop(2, (int *)&args->saddr[0])]++ }'
```

Maybe the first will work? And maybe this is a vote in favor of pass-by-reference #30

**Comment by mmarchini** [comment]
Can we close this? The original issue is fixed and the remaining requests are not bugs (we might want to create new issues for those, although they seem to be covered by #553 and #554).

**Comment by ZekeMedley** [comment]
We were recently able to do this fine by using `ntop(args->src)` for `tracepoint:fib:fib_table_lookup` which has the same `__u8 src[4]` representation of the ip address. It seems like this was likely fixed elsewhere / can now be closed.
