### ISSUE TITLE
INSTALL.md should mention the Ubuntu snap package

### ISSUE THREAD

**Issue by gslavin** [iovisor/bpftrace#531]
While I love using bpftrace, the installation process has been a pain. I've run into issues building bpftrace with both Ubuntu 16.04 (see #507 and #211) and Ubuntu 18.04 (see #389), which are both extremely common platforms. 

After digging through more issues, I discovered there's an Ubuntu snap package for bpftrace (see https://snapcraft.io/bpftrace) and, I think this should be mentioned on the INSTALL.md page.

**Comment by brendangregg** [comment]
Yes, we should document it.

Other people are going to have to help sort out the Ubuntu packaging problems. We have come a long way, and have things packaged in Debian and Canonical, but there are still version differences to sort out. I've done work on packaging, and have finally done an internal build of bpftrace so that Netflix can use it. Facebook have done the same. Our time to work on packaging so that other companies can run it is not infinite, and I've already spent too much time on this. It's better I say this than leave people wondering why we aren't still working on Ubuntu packaging.

**Comment by gslavin** [comment]
Thanks for the quick response, I've created #532 to update the install documentation.

**Comment by gslavin** [comment]
The documentation has been updated, so I'll close this issue.
