### ISSUE TITLE
Should uprobes attach to the binary's shared library functions?

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#556]
If our `executable` has a shared library `lib`, and the user tries to attach to a function defined in `lib` by using `uprobe:executable:function_name`, should bpftrace resolve the shared library path and attach to it, or should the user change the program to use `uprobe:lib:function_name` instead?

**Comment by brendangregg** [comment]
I think `uprobe:lib:function_name`, since that's its location. Since the symbol won't exist in the executable, and we can see from the symbol table that it's a valid symbol but external, we could print a warning for `uprobe:executable:function_name` to say something like "symbol not found in executable: use its library location instead".

**Comment by tyroguru** [comment]
This one needs thinking through carefully as the current situation is not particularly good.

Take a "simple" example (it's actually not simple) of having a C based application and we want to instrument calls to memcpy() (for our purposes here we can say that the application is compiled `-fno-builtin` so that we actually get call sites). Now to instrument `memcpy` I need to know what library is providing the implementation and we obviously don't know that until after plt fixup and it depends upon how the application has been built and/or the runtime environment. Whatever, the person tracing the application most likely will have no idea how to write the probe specification.

I've just done this example and to figure out what to actually probe I needed to step through memcpy calls with gdb to figure out that the implementation for memcpy is actually coming from `/lib64/libc.so.6/__memcpy_ssse3_back`.

Take the example of gdb: you don't need to know who provides your implementation but you simply have to see, "hey gdb, set me a breakpoint on memcpy()". It then changes the breakpoint location as the program executes, first trapping on ld.so's private implementation and then on the libc version that is fixed up by the plt fixup process.

I get exactly why @brendangregg would say to specify the library but knowing where that resides just feels too hard. Also, when I'm focussing on an application I kind of want my probe specification to be relative to that process, i.e., 'uprobe:process:lib:function' - it just kind of feels more natural somehow. It also feels like this way of specifying should let me do `uprobe:process:*:function` so that I match any target function the processes image or linked library.

**Comment by jordalgo** [comment]
Closing as you can now use the wildcard as a target (along with pid targeting) and we'll search for uprobes in everything in proc/pid/maps: https://github.com/iovisor/bpftrace/pull/2757
