### ISSUE TITLE
Tests depend on systemtap-sdt-dev

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#590]
This package isn't available on all distros (e.g. Alpine, Arch), so `#include <sys/sdt.h>` in ` tests/testprogs/usdt_test.c` is breaking the build.

This program should not be compiled and related tests not run if this library is not available.

**Comment by brendangregg** [comment]
Facebook hit this too and have their own sdt.h in an open source repo somewhere (trying to remember).

**Comment by brendangregg** [comment]
https://github.com/facebook/folly/blob/master/folly/tracing/StaticTracepoint.h

**Comment by bd4** [comment]
I am also running into this on Arch Linux (manjaro flavor). Building with 'make bpftrace' skips the tests when building, but 'make install' still tries to run them, and I haven't figured out an obvious workaround yet. Just dropping StaticTracepoint.h into `/usr/include/sys/sdt.h` doesn't quite work - it includes other folly header files. I tried linking the entire 'folly' directory into `/usr/include/folly`, that got me to an include failure on `#include <cstddef>` (seems like this should just work??). Will keep trying, interested to here if anyone else has an easy fix to get past this. I think I may try doing a manual install, since the build worked.

**Comment by bd4** [comment]
This worked for me as a quick workaround:
```
make bpftrace
make man
# edit Makefile install rule by removing the 'preinstall' dependency
sudo make install
```

**Comment by danobi** [comment]
Funny, I was just staring at the folly tracepoint stuff yesterday.

@bd4, copy pasting the folly stuff won't work. The macros all have different names.

I don't see any issues with bpftrace supplying its own `sys/sdt.h` and compiling with that. The probe format in the ELF notes section should be stable enough. Also, it's just for tests so if something breaks it's not a big deal to fix it.
