### ISSUE TITLE
Re-implement elapsed builtin

### ISSUE THREAD

**Issue by ajor** [iovisor/bpftrace#630]
As it's currently implemented the elapsed builtin records the time during compilation and then performs the equivalent of `nsecs - [compilation timestamp]` at runtime. Baking in this value at compile time limits our ability to separate the bpftrace compiler and runtime in the future.

I can see two options:
1. Deprecate and eventually remove the elapsed builtin
A program currently using it such as:
```
tracepoint:syscalls:sys_enter_read
{
  printf("%d\n", elapsed);
}
```

Would have to be rewritten to:
```
BEGIN
{
  @trace_start = nsecs;
}
tracepoint:syscalls:sys_enter_read
{
  printf("%d\n", nsecs - @trace_start);
}
```

2. Re-implement the elapsed builtin to essentially automatically perform the rewrite described above.

Option 2 would be a lot more work, so depends on how important people feel this builtin is. If this work isn't going to be done then it'll have to be option 1.

**Comment by brendangregg** [comment]
It does & will get used a lot. But yes, thanks for digging into it as we
don't want the current limitation.

Can elapsed be rewritten to @__bpf_elapsed, and a BEGIN probe be
automatically added that sets it

**Comment by mmarchini** [comment]
We could implement it as follow:

1. Add a probe before BEGIN which will save the current timestamp to a map. Add this probe only if there was a elapsed call in one of our probes.
2. When `elapsed()` is called, IR will be generated as `current timestamp - saved timestamp`

We don't need to expose the BPF map holding the timestamp to the user. This way we avoid changes to our API.

The probe can be implemented similar to BEGIN, since we don't have a way to run a one-shot probe yet.

**Comment by brendangregg** [comment]
Right, that implementation sounds good.
