### ISSUE TITLE
anonymous map incorrectly gets special treatment

### ISSUE THREAD

**Issue by tyroguru** [iovisor/bpftrace#640]
Take the following script:

```
t:syscalls:sys_enter_write
/tid == 1414349/
{
        @ts[tid] = nsecs;
}

t:syscalls:sys_exit_write
/@ts[tid]/
{
        @h[probe] = hist(nsecs - @a[tid]);
        @[tid] = 0;
}
```
Obvious user error as we are reading from an undefined map so we get:
```
# bpftrace ./t1.bt
Undefined map: @a
TYpe mismatch for '-': comparing 'integer' with 'none'
```

However, if we change the named map `@a` to be the anonymous map then a read returns 0. When we have multiple maps in use we should treat the anonymous map the same as any other as it could lead to surprising results especially in larger scripts where it's not so easy to spot simple typo type errors.

```
t:syscalls:sys_enter_write
/tid == 1414349/
{
        @ts[tid] = nsecs;
}

t:syscalls:sys_exit_write
/@ts[tid]/
{
        @h[probe] = hist(nsecs - @[tid]);
        @[tid] = 0;
}

# bpftrace ./t1.bt
Attaching 2 probes...
```

**Comment by mmarchini** [comment]
`@[tid]` is defined in the line below, which is why it returns 0.

In the example below we replace `@[tid]` with `@a[tid]`, and things keep working:

```
# cat script.bt
t:syscalls:sys_enter_write
/tid == 1414349/
{
        @ts[tid] = nsecs;
}

t:syscalls:sys_exit_write
/@ts[tid]/
{
        @h[probe] = hist(nsecs - @a[tid]);
        @a[tid] = 0;
}

# bpftrace script.bt
Attaching 2 probes...
```

If we remove the line `@[tid] = 0;` from the original script, it will fail:

```
# cat script.bt
t:syscalls:sys_enter_write
/tid == 1414349/
{
        @ts[tid] = nsecs;
}

t:syscalls:sys_exit_write
/@ts[tid]/
{
        @h[probe] = hist(nsecs - @[tid]);
}

# bpftrace script.bt
Undefined map: @
Type mismatch for '-': comparing 'integer' with 'none'
```

So anonymous maps are not being specially treated.

This is the desired `map`s behavior (as I elaborated in https://github.com/iovisor/bpftrace/pull/486#issuecomment-499212466). It should be better documented though.

(I'll close this since it's working as expected, but feel free to reopen if you believe there's anything left to be discussed here)
