### ISSUE TITLE
Build fails against bcc 0.9.0

### ISSUE THREAD

**Issue by jonhoo** [iovisor/bpftrace#649]
When trying to build `bpftrace` against `bcc 0.9.0`, I get:
```
bpftrace-git/src/bpftrace/src/attached_probe.cpp: In member function ‘void bpftrace::AttachedProbe::load_prog()’:
bpftrace-git/src/bpftrace/src/attached_probe.cpp:368:15: error: ‘bpf_prog_load’ was not declared in this scope
     progfd_ = bpf_prog_load(progtype(probe_.type), namep,
               ^~~~~~~~~~~~~
bpftrace-git/src/bpftrace/src/attached_probe.cpp:368:15: note: suggested alternative: ‘bcc_prog_load’
     progfd_ = bpf_prog_load(progtype(probe_.type), namep,
               ^~~~~~~~~~~~~
               bcc_prog_load
```

**Comment by jonhoo** [comment]
This seems like it's a repeat of #472, but it is not a duplicate of #453 (which was fixed in #474).

**Comment by fbs** [comment]
Got more info on your OS and setup? Did you build bcc from source or packaged?

**Comment by jonhoo** [comment]
This is on Arch Linux, `bcc 0.9.0` built from source (specifically [this package](https://aur.archlinux.org/packages/bcc) built [this way](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bcc#n25)).

**Comment by dalehamel** [comment]
did you try building from source with submodules in sync?

I've seen this error before when the bcc submodules are out of sync

**Comment by jonhoo** [comment]
I'm not entirely sure how that would cause this issue? But also, this is using the released versions of `bcc` (i.e., the released tarball), so presumably everything is then going to be in sync, no?

**Comment by dalehamel** [comment]
I believe that `bpf_prog_load` is/was part of libbpf, which was moved into the kernel.

Do you have any other versions of bcc installed that might conflict? I forget exactly what the issue was for me, but it was some combination of not having the submodules be in-sync or otherwise finding the wrong headers.

**Comment by jonhoo** [comment]
I believe `bcc 0.8` worked just fine, so it might be that the later versions do not have `bpf_prog_load`. Just tried `bcc 0.10` (which was recently released), and that doesn't work either. Are you able to compile `bpftrace` when building `bcc` from the 0.9 or 0.10 tarballs?

**Comment by caringi** [comment]
@jonhoo have you created a new build directory (rerun cmake) after the update to bcc 0.9?
Like:

```
mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release ..
make -j4
```

**Comment by dalehamel** [comment]
> I believe bcc 0.8 worked just fine, so it might be that the later versions do not have bpf_prog_load. Just tried bcc 0.10 (which was recently released), and that doesn't work either. Are you able to compile bpftrace when building bcc from the 0.9 or 0.10 tarballs?

Yes i had similar issues going from 0.8 to 0.9, which i think is when the refactor happened.

I recall that they moved these headers to a different location for compatibility, but I don't think they are included in the bcc package anymore.

I'm pretty sure your issue is that the include path bpftrace is using doesn't have the libbpf headers it is expecting to get from bcc, because bcc isn't installing that development header.

If you clone bcc frome source, install all submodules, and install it to your system I bet you'll be able to get bpftrace to build against it, that's how i've been doing it on Gentoo, which should be a similar story to Arch.

**Comment by jonhoo** [comment]
Ah, it looks like Arch separated out `libbpf` into its own package a little while back, so `bcc` wasn't responsible for installing those. Once I installed the `bpf` package (which now needs to be added to the `bpftrace` package), everything works just fine. Sorry for the noise!
