### ISSUE TITLE
`max()` not recognized anymore when including kernel headers

### ISSUE THREAD

**Issue by lberki** [iovisor/bpftrace#692]
This code snippet:

```
#include <linux/kernel.h>
tracepoint:kmem:mm_page_alloc {
  @foo[pid] = max(0);
}
```

Fails to compile with `8.21: syntax error, unexpected ","`. 

Removing the `#include` line makes it work.

`linux/kernel.h` is not that interesting, but a lot of other headers (e.g. `linux/sched.h`) include it so those preclude using max(), too.

As a shot in the dark, I tried adding `#undef max` after the include statement, without success.

`bpftrace --version` yields `bpftrace v0.9-75-g94b8.` 

OS is Ubuntu 18.04 with kernel 4.15.0-50-generic . bpftrace was installed by `snap install bpftrace`.

**Comment by mmarchini** [comment]
Builtins shouldn't have this problem, since they are defined in `lexer.l` (which is where macros are expanded).

```
# cat test.bt
#define cpu invalidName
BEGIN {
  @a = cpu;
  exit();
}
# bpftrace test.bt
Attaching 1 probe...


@a: 0

```

But calls (functions) are not builtins, so they have no protection to be overridden by 

```
# cat test.bt
#define count invalidName
BEGIN {
  @a = count();
  exit();
}
# bpftrace test.bt
Unknown function: 'invalidName'

```

Defining function names in the lexer should be enough to avoid this issue:

```diff
diff --git a/src/lexer.l b/src/lexer.l
index e9a2631..a5e18af 100644
--- a/src/lexer.l
+++ b/src/lexer.l
@@ -49,6 +49,8 @@ path   :(\\.|[_\-\./a-zA-Z0-9#])*:
 
 pid|tid|cgroup|uid|gid|nsecs|cpu|comm|kstack|stack|ustack|arg[0-9]|retval|func|probe|curtask|rand|ctx|username|args|elapsed {
                           return Parser::make_BUILTIN(yytext, loc); }
+count|max|min {
+                          return Parser::make_IDENT(yytext, loc); }
 bpftrace|perf {
                           return Parser::make_STACK_MODE(yytext, loc); }
 {int}                   { return Parser::make_INT(strtoll(yytext, NULL, 0), loc); }
```

With this, your script works:

```
# cat test2.bt
#include <linux/kernel.h>
tracepoint:kmem:mm_page_alloc {
  @foo[pid] = max(0);
}

# bpftrace test2.bt
Attaching 1 probe...
^C

@foo[940]: 0
@foo[1481]: 0
@foo[874]: 0
@foo[13353]: 0
@foo[14378]: 0
@foo[13526]: 0
@foo[13682]: 0
@foo[13163]: 0
@foo[15610]: 0
@foo[14146]: 0
@foo[246]: 0
@foo[20747]: 0
@foo[13261]: 0
@foo[13251]: 0
@foo[14134]: 0
@foo[13279]: 0
@foo[13573]: 0
@foo[14527]: 0

```

We could even go one step further and define a CALL type on the lexer. That way we can validate earlier if a function exists (before semantic analyser) and the implementation of builtin and call will be more coherent. @ajor thoughts?
