### ISSUE TITLE
Right approach to install bpftrace on docker containers

### ISSUE THREAD

**Issue by sattishv** [iovisor/bpftrace#836]
Hi Team,

Couple of questions on the right approach of installing bpftrace on linux.

1. How different is installing bpftrace from source rather than using snap. Since we are on ubuntu trusty finding lot of challenges in installing bpftrace from source on host. BCC installation went well but installing clang had challenges.
2. If we install bpftrace through snap will all the features like accessing kernel files would be available for snap installation as like the source installation because we notice few issues.
3. Since we are docker world which would be the ideal location to install bpftrace. Is it host or inside the container. Installing on host should allow as to attach seamlessly to JVM PID.
Which one would be good (on host or container.)

Thanks
Sattish.

**Comment by danobi** [comment]
Hi,

1. In theory they should be the same but we've noticed issues with snap's security mechanisms. @ColinIanKing is looking into it in #829. Hopefully this gets resolved.
2. See 1
3. In theory there can be issues if the container is inside a different pid namespace. We're working on getting more bpf helpers in so that we can avoid problems. Most of the bpftrace stuff I've run in containers (not docker) worked just fine. However, your mileage may vary so please report any bugs you find. I'm planning on making bpftrace have first class support for use inside containers.

**Comment by sattishv** [comment]
Thanks for your clarifications. Appreciate your response.

**Comment by mmarchini** [comment]
Closing as this was answered. Feel free to reopen (or open a new issue) if you have follow-up questions.
