### ISSUE TITLE
Add LLVM 9 to CI

### ISSUE THREAD

**Issue by mmarchini** [iovisor/bpftrace#908]
LLVM 9.0 was released a few days ago. It's probably a good idea to add it to our CI (and to fix any issues we might encounter while doing it).

**Comment by fbs** [comment]
I'll give this a go. ORCv1 has been deprecated but not yet removed so I'll stick to legacy for now.

The biggest "issue" seems to be codegen changes like:

```
-declare void @llvm.lifetime.start.p0i8(i64, i8* nocapture) #1
+declare void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #1
```

Which breaks all the codegen tests. Instead of adding another #if statement I'll add a rewriter that rewrites it into the format expected by LLVM.
