### ISSUE TITLE
call graph generating

### ISSUE THREAD

**Issue by SchrodingerZhu** [iovisor/bpftrace#976]
I run into a problem in recent research: I need to trace the calling relation of a given set of functions in a user state program (mainly the calling frequency). `bpftrace` should be proper to achieve this goal. However, it seems that `bpftrace`'s stack related functions do not work in some cases (**failed to compile, complaining about a struct related to call stack**). Also, if I trace some low-level functions like `xmalloc`, there will be a great slow down of the program and the tracer may lose some calls. 

Therefore, I am writing this issue to ask whether there is a recommended way to achieve my goal with `bpftrace`.

**Comment by brendangregg** [comment]
Create a CPU flame graph (based on timed sampling, e.g., 99 Hertz), then search the CPU profile for xmalloc paths. This low-overhead approach will reveal the main call paths for xmalloc. Since it's sampling it may miss some infrequent calls entirely which won't appear in the flame graph, but you can't see everything without tracing everything and paying an overhead penalty.
