### ISSUE TITLE
Help needed getting bpftrace to work with very simple C process and USDT probes

### ISSUE THREAD

**Issue by simonhf** [iovisor/bpftrace#987]
Here's the simple C source code:

```
$ cat foo.c
#include <stdio.h>
#include <sys/sdt.h>

int bar(int r, int i) {
    DTRACE_PROBE2(foo, bar_enter, r, i);
    int result = r + i;
    DTRACE_PROBE1(foo, bar_leave, result);
    return(result);
}

int main(void) {
    DTRACE_PROBE(foo, main_enter);
    int r = 0;
    for(int i = 1; i <= 10; i ++) {
        r = bar(r, i);
    }
    printf("- r=%d\n", r);
    DTRACE_PROBE(foo, main_leave);
}
```

Compiled and run:

```
$ gcc -g -o foo foo.c && time ./foo
- r=55
real    0m0.002s
```

bpftrace can list the USDT probes:

```
$ sudo bpftrace -l 'usdt:./foo:*'
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
usdt:./foo:foo:main_enter
usdt:./foo:foo:main_leave
```

But no attempts to get get bpftrace to run ./foo after enabling the probes, seem to work:

```
$ sudo bpftrace -e 'usdt:./foo:* { printf("%s\n", probe); }' -c './foo'
Attaching 4 probes...
Error finding or enabling probe: usdt:./foo:foo:main_leave
^Cfailed to read 'go' pipe: Interrupted system call
Failed to spawn child=./foo
```

```
$ sudo bpftrace -e 'usdt::* { printf("%s\n", probe); }' -c './foo'
usdt probe must specify at least path or pid to probe
```

How to get this to work?

Thanks!

**Comment by fbs** [comment]
What I think happens here (didn't dig into the usdt code much), is that we try to attach the usdt to the pid of the process that is going to be ./foo but it isn't foo yet, it is still a `fork` of bpftrace. The problem here is that we cannot control a program after we've done an `execve`. The program will start running and might even finish before bpftrace is done loading everything into the kernel. So what we do instead is:

- create a pipe
- fork 
 - child will block on the pipe, waiting for data(a signal) to be sent
- the parent (bpftrace) will continue setting up everything, maps probes etc
- once bpftrace is ready to go it tells the child to run
 - the child execves

As the execve happens after the probes are installed `-c` cannot work with usdts.

It would be nice if we somehow pause the child after execve as that would make it possible to attach usdts and control when it starts running. The only real option for that appears to be using ptrace but I haven't looked into the downsides of that yet.

For now the only option is to use 2 terminals, one for bpftrace and one for foo:

```
$ sudo bpftrace -e 'usdt:./foo:* { printf("%s\n", probe); }'
Attaching 4 probes...
usdt:./foo:foo:main_enter
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
```

**Comment by simonhf** [comment]
Thanks. I got it to work with this command which simulates starting another terminal :-)

```
$ sudo bpftrace -e 'usdt:./foo:* { printf("%s\n", probe); }' & (sleep 2 ; ./foo)
[10] 7208
Attaching 4 probes...
usdt:./foo:foo:main_enter
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
- r=55
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
usdt:./foo:foo:bar_enter
usdt:./foo:foo:bar_leave
usdt:./foo:foo:main_leave
$ sudo killall bpftrace
[10]   Terminated              sudo bpftrace -e 'usdt:./foo:* { printf("%s\n", probe); }'
$ 
```
